In [ ]:
import pandas as pd

# --- CONFIGURATION ---
# Replace the following with your own source paths
RAW_CITIES_PATH = "/data/raw/worldcities.csv"
RAW_CONTINENTS_PATH = "/data/raw/country_continents.csv"
PROCESSED_OUTPUT_PATH = "/data/processed/capital_city_locations.csv"

city = pd.read_csv(RAW_CITIES_PATH)
cont = pd.read_csv(RAW_CONTINENTS_PATH)

In [13]:
city.head()

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
0,Tokyo,Tokyo,35.6897,139.6922,Japan,JP,JPN,Tōkyō,primary,37732000.0,1392685764
1,Jakarta,Jakarta,-6.1750,106.8275,Indonesia,ID,IDN,Jakarta,primary,33756000.0,1360771077
2,Delhi,Delhi,28.6100,77.2300,India,IN,IND,Delhi,admin,32226000.0,1356872604
3,Guangzhou,Guangzhou,23.1300,113.2600,China,CN,CHN,Guangdong,admin,26940000.0,1156237133
4,Mumbai,Mumbai,19.0761,72.8775,India,IN,IND,Mahārāshtra,admin,24973000.0,1356226629

In [ ]:
# Filter out city table to only include primary (capital) cities
city_capital = city[city['capital'] == 'primary']
city_capital.head()

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
0,Tokyo,Tokyo,35.6897,139.6922,Japan,JP,JPN,Tōkyō,primary,37732000.0,1392685764
1,Jakarta,Jakarta,-6.1750,106.8275,Indonesia,ID,IDN,Jakarta,primary,33756000.0,1360771077
5,Manila,Manila,14.5958,120.9772,Philippines,PH,PHL,Manila,primary,24922000.0,1608618140
8,Seoul,Seoul,37.5600,126.9900,South Korea,KR,KOR,Seoul,primary,23016000.0,1410836482
9,Mexico City,Mexico City,19.4333,-99.1333,Mexico,MX,MEX,Ciudad de México,primary,21804000.0,1484247881

In [17]:
cont.head()

  Continent   Country
0    Africa   Algeria
1    Africa    Angola
2    Africa     Benin
3    Africa  Botswana
4    Africa   Burkina

In [ ]:
# Join capital city table with continent-country table on country name
final = pd.merge(city_capital, cont, left_on='country', right_on='Country', how='inner')

In [24]:
final.head()

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id,Continent,Country
0,Tokyo,Tokyo,35.6897,139.6922,Japan,JP,JPN,Tōkyō,primary,37732000.0,1392685764,Asia,Japan
1,Jakarta,Jakarta,-6.1750,106.8275,Indonesia,ID,IDN,Jakarta,primary,33756000.0,1360771077,Asia,Indonesia
2,Manila,Manila,14.5958,120.9772,Philippines,PH,PHL,Manila,primary,24922000.0,1608618140,Asia,Philippines
3,Seoul,Seoul,37.5600,126.9900,South Korea,KR,KOR,Seoul,primary,23016000.0,1410836482,Asia,South Korea
4,Mexico City,Mexico City,19.4333,-99.1333,Mexico,MX,MEX,Ciudad de México,primary,21804000.0,1484247881,North America,Mexico

In [ ]:
# Remove extra country column
final_new = final.drop(columns='Country')
final_new.head()

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id,Continent
0,Tokyo,Tokyo,35.6897,139.6922,Japan,JP,JPN,Tōkyō,primary,37732000.0,1392685764,Asia
1,Jakarta,Jakarta,-6.1750,106.8275,Indonesia,ID,IDN,Jakarta,primary,33756000.0,1360771077,Asia
2,Manila,Manila,14.5958,120.9772,Philippines,PH,PHL,Manila,primary,24922000.0,1608618140,Asia
3,Seoul,Seoul,37.5600,126.9900,South Korea,KR,KOR,Seoul,primary,23016000.0,1410836482,Asia
4,Mexico City,Mexico City,19.4333,-99.1333,Mexico,MX,MEX,Ciudad de México,primary,21804000.0,1484247881,North America

In [ ]:
final_new.to_csv(PROCESSED_OUTPUT_PATH)